[package]
name = "sightglass-analysis"
version = "0.1.0"
authors = ["Sightglass Project Developers"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
behrens-fisher = "0.1.0"
sightglass-data = { path = "../data" }
