[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
brotli = "7.0"
sightglass-api = "0.1"

[workspace]
